site_name: pssac
site_url: https://seisman.github.io/pssac
docs_dir: .
repo_url: https://github.com/seisman/pssac
theme: material
pages:
- Introduction: index.md
- Usage: usage.md
- Gallery: gallery.md

extra:
  version: '0.1.1'
  author:
    github: 'seisman'
